### ISSUE TITLE
Update tern-plot ontology to use published version of ssn-ext

### ISSUE THREAD

**Issue by dr-shorthair** [ternaustralia/ontology_tern-plot#1]
In the revised/published version of ssn-ext
https://www.w3.org/TR/vocab-ssn-ext/
https://raw.githack.com/w3c/sdw/gh-pages/ssn-extensions/rdf/ssn-ext.ttl

`ObservationCollection` is now in the SOSA namespace - i.e. `http://www.w3.org/ns/sosa/ObservationCollection`. 

The deployed version of tern-plot and datasets conforming use a different namespace. Needs bringing into line now.

**Comment by dr-shorthair** [comment]
See https://www.w3.org/ns/ssn/ext/

**Comment by edmondchuc** [comment]
Plot ontology imports from the new location of ssn-ext now.
